# Generated by Django 4.0.6 on 2022-07-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthLibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reaction',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='auth_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippet', to='AuthLibrary.codesnippet'),
        ),
    ]
