# Generated by Django 4.0.6 on 2022-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthLibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=-1)),
                ('no_of_vote', models.PositiveIntegerField()),
            ],
        ),
    ]
