# Generated by Django 4.0.6 on 2022-07-31 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthLibrary', '0002_remove_comment_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='auth_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippet', to='AuthLibrary.authlibrary'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
