# Generated by Django 4.0.6 on 2022-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthLibrary', '0002_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('no_of_vote', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
