# Generated by Django 4.0.6 on 2022-08-01 19:26

import AuthLibrary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthLibrary', '0003_alter_codesnippet_auth_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlibrary',
            name='image',
            field=models.ImageField(null=True, upload_to=AuthLibrary.models.auth_lib_image_file_path),
        ),
    ]
