# Generated by Django 4.0.6 on 2022-07-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthLibrary', '0003_reaction_delete_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='authlibrary',
            name='code_snippets',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='AuthLibrary.codesnippet'),
        ),
    ]
